CREATE TABLE `paises` (
`id_pais` int(11) NOT NULL AUTO_INCREMENT,
`iso` char(2) DEFAULT NULL,
`nombre` varchar(80) DEFAULT NULL,
`gentilicio` varchar(80) DEFAULT NULL,
PRIMARY KEY (`id_pais`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
 
INSERT INTO `paises` VALUES(1, 'AF', 'Afganistán', 'gentilicio');
INSERT INTO `paises` VALUES(2, 'AX', 'Islas Gland', 'gentilicio');
INSERT INTO `paises` VALUES(3, 'AL', 'Albania', 'gentilicio');
INSERT INTO `paises` VALUES(4, 'DE', 'Alemania', 'gentilicio');
INSERT INTO `paises` VALUES(5, 'AD', 'Andorra', 'gentilicio');
INSERT INTO `paises` VALUES(6, 'AO', 'Angola', 'gentilicio');
INSERT INTO `paises` VALUES(7, 'AI', 'Anguilla', 'gentilicio');
INSERT INTO `paises` VALUES(8, 'AQ', 'Antártida', 'gentilicio');
INSERT INTO `paises` VALUES(9, 'AG', 'Antigua y Barbuda', 'gentilicio');
INSERT INTO `paises` VALUES(10, 'AN', 'Antillas Holandesas', 'gentilicio');
INSERT INTO `paises` VALUES(11, 'SA', 'Arabia Saudí', 'gentilicio');
INSERT INTO `paises` VALUES(12, 'DZ', 'Argelia', 'gentilicio');
INSERT INTO `paises` VALUES(13, 'AR', 'Argentina', 'gentilicio');
INSERT INTO `paises` VALUES(14, 'AM', 'Armenia', 'gentilicio');
INSERT INTO `paises` VALUES(15, 'AW', 'Aruba', 'gentilicio');
INSERT INTO `paises` VALUES(16, 'AU', 'Australia', 'gentilicio');
INSERT INTO `paises` VALUES(17, 'AT', 'Austria', 'gentilicio');
INSERT INTO `paises` VALUES(18, 'AZ', 'Azerbaiyán', 'gentilicio');
INSERT INTO `paises` VALUES(19, 'BS', 'Bahamas', 'gentilicio');
INSERT INTO `paises` VALUES(20, 'BH', 'Bahréin', 'gentilicio');
INSERT INTO `paises` VALUES(21, 'BD', 'Bangladesh', 'gentilicio');
INSERT INTO `paises` VALUES(22, 'BB', 'Barbados', 'gentilicio');
INSERT INTO `paises` VALUES(23, 'BY', 'Bielorrusia', 'gentilicio');
INSERT INTO `paises` VALUES(24, 'BE', 'Bélgica', 'gentilicio');
INSERT INTO `paises` VALUES(25, 'BZ', 'Belice', 'gentilicio');
INSERT INTO `paises` VALUES(26, 'BJ', 'Benin', 'gentilicio');
INSERT INTO `paises` VALUES(27, 'BM', 'Bermudas', 'gentilicio');
INSERT INTO `paises` VALUES(28, 'BT', 'Bhután', 'gentilicio');
INSERT INTO `paises` VALUES(29, 'BO', 'Bolivia', 'gentilicio');
INSERT INTO `paises` VALUES(30, 'BA', 'Bosnia y Herzegovina', 'gentilicio');
INSERT INTO `paises` VALUES(31, 'BW', 'Botsuana', 'gentilicio');
INSERT INTO `paises` VALUES(32, 'BV', 'Isla Bouvet', 'gentilicio');
INSERT INTO `paises` VALUES(33, 'BR', 'Brasil', 'gentilicio');
INSERT INTO `paises` VALUES(34, 'BN', 'Brunéi', 'gentilicio');
INSERT INTO `paises` VALUES(35, 'BG', 'Bulgaria', 'gentilicio');
INSERT INTO `paises` VALUES(36, 'BF', 'Burkina Faso', 'gentilicio');
INSERT INTO `paises` VALUES(37, 'BI', 'Burundi', 'gentilicio');
INSERT INTO `paises` VALUES(38, 'CV', 'Cabo Verde', 'gentilicio');
INSERT INTO `paises` VALUES(39, 'KY', 'Islas Caimán', 'gentilicio');
INSERT INTO `paises` VALUES(40, 'KH', 'Camboya', 'gentilicio');
INSERT INTO `paises` VALUES(41, 'CM', 'Camerún', 'gentilicio');
INSERT INTO `paises` VALUES(42, 'CA', 'Canadá', 'gentilicio');
INSERT INTO `paises` VALUES(43, 'CF', 'República Centroafricana', 'gentilicio');
INSERT INTO `paises` VALUES(44, 'TD', 'Chad', 'gentilicio');
INSERT INTO `paises` VALUES(45, 'CZ', 'República Checa', 'gentilicio');
INSERT INTO `paises` VALUES(46, 'CL', 'Chile', 'gentilicio');
INSERT INTO `paises` VALUES(47, 'CN', 'China', 'gentilicio');
INSERT INTO `paises` VALUES(48, 'CY', 'Chipre', 'gentilicio');
INSERT INTO `paises` VALUES(49, 'CX', 'Isla de Navidad', 'gentilicio');
INSERT INTO `paises` VALUES(50, 'VA', 'Ciudad del Vaticano', 'gentilicio');
INSERT INTO `paises` VALUES(51, 'CC', 'Islas Cocos', 'gentilicio');
INSERT INTO `paises` VALUES(52, 'CO', 'Colombia', 'gentilicio');
INSERT INTO `paises` VALUES(53, 'KM', 'Comoras', 'gentilicio');
INSERT INTO `paises` VALUES(54, 'CD', 'República Democrática del Congo', 'gentilicio');
INSERT INTO `paises` VALUES(55, 'CG', 'Congo', 'gentilicio');
INSERT INTO `paises` VALUES(56, 'CK', 'Islas Cook', 'gentilicio');
INSERT INTO `paises` VALUES(57, 'KP', 'Corea del Norte', 'gentilicio');
INSERT INTO `paises` VALUES(58, 'KR', 'Corea del Sur', 'gentilicio');
INSERT INTO `paises` VALUES(59, 'CI', 'Costa de Marfil', 'gentilicio');
INSERT INTO `paises` VALUES(60, 'CR', 'Costa Rica', 'gentilicio');
INSERT INTO `paises` VALUES(61, 'HR', 'Croacia', 'gentilicio');
INSERT INTO `paises` VALUES(62, 'CU', 'Cuba', 'gentilicio');
INSERT INTO `paises` VALUES(63, 'DK', 'Dinamarca', 'gentilicio');
INSERT INTO `paises` VALUES(64, 'DM', 'Dominica', 'gentilicio');
INSERT INTO `paises` VALUES(65, 'DO', 'República Dominicana', 'gentilicio');
INSERT INTO `paises` VALUES(66, 'EC', 'Ecuador', 'gentilicio');
INSERT INTO `paises` VALUES(67, 'EG', 'Egipto', 'gentilicio');
INSERT INTO `paises` VALUES(68, 'SV', 'El Salvador', 'gentilicio');
INSERT INTO `paises` VALUES(69, 'AE', 'Emiratos Árabes Unidos', 'gentilicio');
INSERT INTO `paises` VALUES(70, 'ER', 'Eritrea', 'gentilicio');
INSERT INTO `paises` VALUES(71, 'SK', 'Eslovaquia', 'gentilicio');
INSERT INTO `paises` VALUES(72, 'SI', 'Eslovenia', 'gentilicio');
INSERT INTO `paises` VALUES(73, 'ES', 'España', 'gentilicio');
INSERT INTO `paises` VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos', 'gentilicio');
INSERT INTO `paises` VALUES(75, 'US', 'Estados Unidos', 'gentilicio');
INSERT INTO `paises` VALUES(76, 'EE', 'Estonia', 'gentilicio');
INSERT INTO `paises` VALUES(77, 'ET', 'Etiopía', 'gentilicio');
INSERT INTO `paises` VALUES(78, 'FO', 'Islas Feroe', 'gentilicio');
INSERT INTO `paises` VALUES(79, 'PH', 'Filipinas', 'gentilicio');
INSERT INTO `paises` VALUES(80, 'FI', 'Finlandia', 'gentilicio');
INSERT INTO `paises` VALUES(81, 'FJ', 'Fiyi', 'gentilicio');
INSERT INTO `paises` VALUES(82, 'FR', 'Francia', 'gentilicio');
INSERT INTO `paises` VALUES(83, 'GA', 'Gabón', 'gentilicio');
INSERT INTO `paises` VALUES(84, 'GM', 'Gambia', 'gentilicio');
INSERT INTO `paises` VALUES(85, 'GE', 'Georgia', 'gentilicio');
INSERT INTO `paises` VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur', 'gentilicio');
INSERT INTO `paises` VALUES(87, 'GH', 'Ghana', 'gentilicio');
INSERT INTO `paises` VALUES(88, 'GI', 'Gibraltar', 'gentilicio');
INSERT INTO `paises` VALUES(89, 'GD', 'Granada', 'gentilicio');
INSERT INTO `paises` VALUES(90, 'GR', 'Grecia', 'gentilicio');
INSERT INTO `paises` VALUES(91, 'GL', 'Groenlandia', 'gentilicio');
INSERT INTO `paises` VALUES(92, 'GP', 'Guadalupe', 'gentilicio');
INSERT INTO `paises` VALUES(93, 'GU', 'Guam', 'gentilicio');
INSERT INTO `paises` VALUES(94, 'GT', 'Guatemala', 'gentilicio');
INSERT INTO `paises` VALUES(95, 'GF', 'Guayana Francesa', 'gentilicio');
INSERT INTO `paises` VALUES(96, 'GN', 'Guinea', 'gentilicio');
INSERT INTO `paises` VALUES(97, 'GQ', 'Guinea Ecuatorial', 'gentilicio');
INSERT INTO `paises` VALUES(98, 'GW', 'Guinea-Bissau', 'gentilicio');
INSERT INTO `paises` VALUES(99, 'GY', 'Guyana', 'gentilicio');
INSERT INTO `paises` VALUES(100, 'HT', 'Haití', 'gentilicio');
INSERT INTO `paises` VALUES(101, 'HM', 'Islas Heard y McDonald', 'gentilicio');
INSERT INTO `paises` VALUES(102, 'HN', 'Honduras', 'gentilicio');
INSERT INTO `paises` VALUES(103, 'HK', 'Hong Kong', 'gentilicio');
INSERT INTO `paises` VALUES(104, 'HU', 'Hungría', 'gentilicio');
INSERT INTO `paises` VALUES(105, 'IN', 'India', 'gentilicio');
INSERT INTO `paises` VALUES(106, 'ID', 'Indonesia', 'gentilicio');
INSERT INTO `paises` VALUES(107, 'IR', 'Irán', 'gentilicio');
INSERT INTO `paises` VALUES(108, 'IQ', 'Iraq', 'gentilicio');
INSERT INTO `paises` VALUES(109, 'IE', 'Irlanda', 'gentilicio');
INSERT INTO `paises` VALUES(110, 'IS', 'Islandia', 'gentilicio');
INSERT INTO `paises` VALUES(111, 'IL', 'Israel', 'gentilicio');
INSERT INTO `paises` VALUES(112, 'IT', 'Italia', 'gentilicio');
INSERT INTO `paises` VALUES(113, 'JM', 'Jamaica', 'gentilicio');
INSERT INTO `paises` VALUES(114, 'JP', 'Japón', 'gentilicio');
INSERT INTO `paises` VALUES(115, 'JO', 'Jordania', 'gentilicio');
INSERT INTO `paises` VALUES(116, 'KZ', 'Kazajstán', 'gentilicio');
INSERT INTO `paises` VALUES(117, 'KE', 'Kenia', 'gentilicio');
INSERT INTO `paises` VALUES(118, 'KG', 'Kirguistán', 'gentilicio');
INSERT INTO `paises` VALUES(119, 'KI', 'Kiribati', 'gentilicio');
INSERT INTO `paises` VALUES(120, 'KW', 'Kuwait', 'gentilicio');
INSERT INTO `paises` VALUES(121, 'LA', 'Laos', 'gentilicio');
INSERT INTO `paises` VALUES(122, 'LS', 'Lesotho', 'gentilicio');
INSERT INTO `paises` VALUES(123, 'LV', 'Letonia', 'gentilicio');
INSERT INTO `paises` VALUES(124, 'LB', 'Líbano', 'gentilicio');
INSERT INTO `paises` VALUES(125, 'LR', 'Liberia', 'gentilicio');
INSERT INTO `paises` VALUES(126, 'LY', 'Libia', 'gentilicio');
INSERT INTO `paises` VALUES(127, 'LI', 'Liechtenstein', 'gentilicio');
INSERT INTO `paises` VALUES(128, 'LT', 'Lituania', 'gentilicio');
INSERT INTO `paises` VALUES(129, 'LU', 'Luxemburgo', 'gentilicio');
INSERT INTO `paises` VALUES(130, 'MO', 'Macao', 'gentilicio');
INSERT INTO `paises` VALUES(131, 'MK', 'ARY Macedonia', 'gentilicio');
INSERT INTO `paises` VALUES(132, 'MG', 'Madagascar', 'gentilicio');
INSERT INTO `paises` VALUES(133, 'MY', 'Malasia', 'gentilicio');
INSERT INTO `paises` VALUES(134, 'MW', 'Malawi', 'gentilicio');
INSERT INTO `paises` VALUES(135, 'MV', 'Maldivas', 'gentilicio');
INSERT INTO `paises` VALUES(136, 'ML', 'Malí', 'gentilicio');
INSERT INTO `paises` VALUES(137, 'MT', 'Malta', 'gentilicio');
INSERT INTO `paises` VALUES(138, 'FK', 'Islas Malvinas', 'gentilicio');
INSERT INTO `paises` VALUES(139, 'MP', 'Islas Marianas del Norte', 'gentilicio');
INSERT INTO `paises` VALUES(140, 'MA', 'Marruecos', 'gentilicio');
INSERT INTO `paises` VALUES(141, 'MH', 'Islas Marshall', 'gentilicio');
INSERT INTO `paises` VALUES(142, 'MQ', 'Martinica', 'gentilicio');
INSERT INTO `paises` VALUES(143, 'MU', 'Mauricio', 'gentilicio');
INSERT INTO `paises` VALUES(144, 'MR', 'Mauritania', 'gentilicio');
INSERT INTO `paises` VALUES(145, 'YT', 'Mayotte', 'gentilicio');
INSERT INTO `paises` VALUES(146, 'MX', 'México', 'gentilicio');
INSERT INTO `paises` VALUES(147, 'FM', 'Micronesia', 'gentilicio');
INSERT INTO `paises` VALUES(148, 'MD', 'Moldavia', 'gentilicio');
INSERT INTO `paises` VALUES(149, 'MC', 'Mónaco', 'gentilicio');
INSERT INTO `paises` VALUES(150, 'MN', 'Mongolia', 'gentilicio');
INSERT INTO `paises` VALUES(151, 'MS', 'Montserrat', 'gentilicio');
INSERT INTO `paises` VALUES(152, 'MZ', 'Mozambique', 'gentilicio');
INSERT INTO `paises` VALUES(153, 'MM', 'Myanmar', 'gentilicio');
INSERT INTO `paises` VALUES(154, 'NA', 'Namibia', 'gentilicio');
INSERT INTO `paises` VALUES(155, 'NR', 'Nauru', 'gentilicio');
INSERT INTO `paises` VALUES(156, 'NP', 'Nepal', 'gentilicio');
INSERT INTO `paises` VALUES(157, 'NI', 'Nicaragua', 'gentilicio');
INSERT INTO `paises` VALUES(158, 'NE', 'Níger', 'gentilicio');
INSERT INTO `paises` VALUES(159, 'NG', 'Nigeria', 'gentilicio');
INSERT INTO `paises` VALUES(160, 'NU', 'Niue', 'gentilicio');
INSERT INTO `paises` VALUES(161, 'NF', 'Isla Norfolk', 'gentilicio');
INSERT INTO `paises` VALUES(162, 'NO', 'Noruega', 'gentilicio');
INSERT INTO `paises` VALUES(163, 'NC', 'Nueva Caledonia', 'gentilicio');
INSERT INTO `paises` VALUES(164, 'NZ', 'Nueva Zelanda', 'gentilicio');
INSERT INTO `paises` VALUES(165, 'OM', 'Omán', 'gentilicio');
INSERT INTO `paises` VALUES(166, 'NL', 'Países Bajos', 'gentilicio');
INSERT INTO `paises` VALUES(167, 'PK', 'Pakistán', 'gentilicio');
INSERT INTO `paises` VALUES(168, 'PW', 'Palau', 'gentilicio');
INSERT INTO `paises` VALUES(169, 'PS', 'Palestina', 'gentilicio');
INSERT INTO `paises` VALUES(170, 'PA', 'Panamá', 'gentilicio');
INSERT INTO `paises` VALUES(171, 'PG', 'Papúa Nueva Guinea', 'gentilicio');
INSERT INTO `paises` VALUES(172, 'PY', 'Paraguay', 'gentilicio');
INSERT INTO `paises` VALUES(173, 'PE', 'Perú', 'gentilicio');
INSERT INTO `paises` VALUES(174, 'PN', 'Islas Pitcairn', 'gentilicio');
INSERT INTO `paises` VALUES(175, 'PF', 'Polinesia Francesa', 'gentilicio');
INSERT INTO `paises` VALUES(176, 'PL', 'Polonia', 'gentilicio');
INSERT INTO `paises` VALUES(177, 'PT', 'Portugal', 'gentilicio');
INSERT INTO `paises` VALUES(178, 'PR', 'Puerto Rico', 'gentilicio');
INSERT INTO `paises` VALUES(179, 'QA', 'Qatar', 'gentilicio');
INSERT INTO `paises` VALUES(180, 'GB', 'Reino Unido', 'gentilicio');
INSERT INTO `paises` VALUES(181, 'RE', 'Reunión', 'gentilicio');
INSERT INTO `paises` VALUES(182, 'RW', 'Ruanda', 'gentilicio');
INSERT INTO `paises` VALUES(183, 'RO', 'Rumania', 'gentilicio');
INSERT INTO `paises` VALUES(184, 'RU', 'Rusia', 'gentilicio');
INSERT INTO `paises` VALUES(185, 'EH', 'Sahara Occidental', 'gentilicio');
INSERT INTO `paises` VALUES(186, 'SB', 'Islas Salomón', 'gentilicio');
INSERT INTO `paises` VALUES(187, 'WS', 'Samoa', 'gentilicio');
INSERT INTO `paises` VALUES(188, 'AS', 'Samoa Americana', 'gentilicio');
INSERT INTO `paises` VALUES(189, 'KN', 'San Cristóbal y Nevis', 'gentilicio');
INSERT INTO `paises` VALUES(190, 'SM', 'San Marino', 'gentilicio');
INSERT INTO `paises` VALUES(191, 'PM', 'San Pedro y Miquelón', 'gentilicio');
INSERT INTO `paises` VALUES(192, 'VC', 'San Vicente y las Granadinas', 'gentilicio');
INSERT INTO `paises` VALUES(193, 'SH', 'Santa Helena', 'gentilicio');
INSERT INTO `paises` VALUES(194, 'LC', 'Santa Lucía', 'gentilicio');
INSERT INTO `paises` VALUES(195, 'ST', 'Santo Tomé y Príncipe', 'gentilicio');
INSERT INTO `paises` VALUES(196, 'SN', 'Senegal', 'gentilicio');
INSERT INTO `paises` VALUES(197, 'CS', 'Serbia y Montenegro', 'gentilicio');
INSERT INTO `paises` VALUES(198, 'SC', 'Seychelles', 'gentilicio');
INSERT INTO `paises` VALUES(199, 'SL', 'Sierra Leona', 'gentilicio');
INSERT INTO `paises` VALUES(200, 'SG', 'Singapur', 'gentilicio');
INSERT INTO `paises` VALUES(201, 'SY', 'Siria', 'gentilicio');
INSERT INTO `paises` VALUES(202, 'SO', 'Somalia', 'gentilicio');
INSERT INTO `paises` VALUES(203, 'LK', 'Sri Lanka', 'gentilicio');
INSERT INTO `paises` VALUES(204, 'SZ', 'Suazilandia', 'gentilicio');
INSERT INTO `paises` VALUES(205, 'ZA', 'Sudáfrica', 'gentilicio');
INSERT INTO `paises` VALUES(206, 'SD', 'Sudán', 'gentilicio');
INSERT INTO `paises` VALUES(207, 'SE', 'Suecia', 'gentilicio');
INSERT INTO `paises` VALUES(208, 'CH', 'Suiza', 'gentilicio');
INSERT INTO `paises` VALUES(209, 'SR', 'Surinam', 'gentilicio');
INSERT INTO `paises` VALUES(210, 'SJ', 'Svalbard y Jan Mayen', 'gentilicio');
INSERT INTO `paises` VALUES(211, 'TH', 'Tailandia', 'gentilicio');
INSERT INTO `paises` VALUES(212, 'TW', 'Taiwán', 'gentilicio');
INSERT INTO `paises` VALUES(213, 'TZ', 'Tanzania', 'gentilicio');
INSERT INTO `paises` VALUES(214, 'TJ', 'Tayikistán', 'gentilicio');
INSERT INTO `paises` VALUES(215, 'IO', 'Territorio Británico del Océano Índico', 'gentilicio');
INSERT INTO `paises` VALUES(216, 'TF', 'Territorios Australes Franceses', 'gentilicio');
INSERT INTO `paises` VALUES(217, 'TL', 'Timor Oriental', 'gentilicio');
INSERT INTO `paises` VALUES(218, 'TG', 'Togo', 'gentilicio');
INSERT INTO `paises` VALUES(219, 'TK', 'Tokelau', 'gentilicio');
INSERT INTO `paises` VALUES(220, 'TO', 'Tonga', 'gentilicio');
INSERT INTO `paises` VALUES(221, 'TT', 'Trinidad y Tobago', 'gentilicio');
INSERT INTO `paises` VALUES(222, 'TN', 'Túnez', 'gentilicio');
INSERT INTO `paises` VALUES(223, 'TC', 'Islas Turcas y Caicos', 'gentilicio');
INSERT INTO `paises` VALUES(224, 'TM', 'Turkmenistán', 'gentilicio');
INSERT INTO `paises` VALUES(225, 'TR', 'Turquía', 'gentilicio');
INSERT INTO `paises` VALUES(226, 'TV', 'Tuvalu', 'gentilicio');
INSERT INTO `paises` VALUES(227, 'UA', 'Ucrania', 'gentilicio');
INSERT INTO `paises` VALUES(228, 'UG', 'Uganda', 'gentilicio');
INSERT INTO `paises` VALUES(229, 'UY', 'Uruguay', 'gentilicio');
INSERT INTO `paises` VALUES(230, 'UZ', 'Uzbekistán', 'gentilicio');
INSERT INTO `paises` VALUES(231, 'VU', 'Vanuatu', 'gentilicio');
INSERT INTO `paises` VALUES(232, 'VE', 'Venezuela', 'gentilicio');
INSERT INTO `paises` VALUES(233, 'VN', 'Vietnam', 'gentilicio');
INSERT INTO `paises` VALUES(234, 'VG', 'Islas Vírgenes Británicas', 'gentilicio');
INSERT INTO `paises` VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos', 'gentilicio');
INSERT INTO `paises` VALUES(236, 'WF', 'Wallis y Futuna', 'gentilicio');
INSERT INTO `paises` VALUES(237, 'YE', 'Yemen', 'gentilicio');
INSERT INTO `paises` VALUES(238, 'DJ', 'Yibuti', 'gentilicio');
INSERT INTO `paises` VALUES(239, 'ZM', 'Zambia', 'gentilicio');
INSERT INTO `paises` VALUES(240, 'ZW', 'Zimbabue', 'gentilicio');